name: Install deps and caching
description: Install deps and caching
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ vars.BUN_VERSION }}
    - uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}

    - name: Install deps
      shell: bash
      run: bun i
