services:
  web:
    image: nisibz/gh-action-react
    container_name: web
    ports:
      - 3000:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - caddy

networks:
  caddy:
    external: true
