name: Deploy react CSR
on:
  push:
    branches:
      - develop
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
  lint:
    # bun tun lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18
      - name: Install dependencies
        run: bun i
      - name: Lint
        run: bun run lint

  deploy:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18
      - name: Install dependencies
        run: bun i
      - name: Build
        run: bun run build
      - name: List dist/
        run: ls dist
      - name: Deploy
        run: echo "Deploying..."
