name: Deploy react CSR
# on: workflow_dispatch
on:
  push:
    branches:
      - develop
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: oven/bun:1
    steps:
      - name: install-cache
        uses: ./.github/actions/install-cache
      - name: Build
        run: bun run build
      - name: List dist/
        run: ls dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/
      # - name: Force fail
      #   run: exit 1
  deploy:
    if: success()
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist/
      - name: Deploy
        run: echo "Deploying..."

  # notify:
  #   needs:
  #     - build
  #     - deploy
  #   runs-on: ubuntu-latest
  #   if: failure()
  #   steps:
  #     - name: Discord notification
  #       env:
  #         DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY
  #       uses: Ilshidur/action-discord@master
  #       with:
  #         rgs: "Build failed by nisibz"
